name: "Hit the REST API"
on:
  push:
    branches:
      - rest-api
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TAG: v.0.0.1
#  API_KEY: "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtZWV0cmFqc2luaC5zb2xhbmtpQGNyZXN0ZGF0YXN5cy5jb20iLCJ1c2VyX3R5cGUiOiJBRE1JTiIsImNvbXBhbnkiOiJmb28iLCJleHAiOjE2OTY5Mzc3NjksImlhdCI6MTY5NjkxOTc2OX0.NWRzG0V9-5j2JLHkwHmm_SuqK9Ro3OUzA44DQGFc7NxMzpuiri73gl2QNpB6T89Y"
  INTEGRATION_ID: 1
  TENANT: foo
  JOB_RUN_NUMBER: ${{github.run_number}}
  JOB_NAME: ${{github.workflow}}
  REPOSITORY: ${{github.repository}}
  API_KEY: ${{ secrets.SEI_API_KEY }}

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: REST API Call to push artifacts to SEI
        id: push_artifacts
        env:
          payload: '{"job_run_number":"${{ env.JOB_RUN_NUMBER }}", "job_name":"${{ env.JOB_NAME }}", "image_name":"${{ env.IMAGE_NAME }}", "image_url":"${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}", "image_tag":"${{ env.TAG }}", "integration_id":"${{ env.INTEGRATION_ID }}", "tenant":"${{ env.TENANT }}", "repository":"${{ env.REPOSITORY }}"}'
        run: curl 'https://651fd848906e276284c39b13.mockapi.io/api/v1/Response' -H 'accept:application/json, text/plain, */*' -H 'accept-language:en-GB,en-US;q=0.9,en;q=0.8' -H 'content-type:application/json' -H 'user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' --data-raw '${{ env.payload }}' --compressed --globoff -o response.json
