name: "Hit the REST API"
on:
  push:
    branches:
      - rest-api
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TAG: v.0.0.1

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: REST API Call with curl
        id: curls
        run: |
          curl 'https://testapi1.propelo.ai/v1/tags/list' -H 'authority:testapi1.propelo.ai' -H 'accept:application/json, text/plain, */*' -H 'accept-language:en-GB,en-US;q=0.9,en;q=0.8' -H 'authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtZWV0cmFqc2luaC5zb2xhbmtpQGNyZXN0ZGF0YXN5cy5jb20iLCJ1c2VyX3R5cGUiOiJBRE1JTiIsImNvbXBhbnkiOiJmb28iLCJleHAiOjE2OTY4NDcxMDYsImlhdCI6MTY5NjgyOTEwNn0.xtKJ5Lag-GB0Ry-IbYZfm1tuRhldhBXIVpGYyjFcALFoUkR8Apl7DYbor2OGDP6Z' -H 'content-type:application/json' -H 'origin:https://testui1.propelo.ai' -H 'referer:https://testui1.propelo.ai/' -H 'user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' --data-raw '{"filter":{"tag_ids":["684","685","686","687"]}}' --compressed --globoff -o tags.json
      - name: Read tags
        id: tag_id
        run: echo "id=$(cat tags.json | jq -c '.records[0].id')" >> $GITHUB_OUTPUT
      - name: print tag
        run: echo ${{ steps.tag_id.outputs.id }}
        
